version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies...
      - npm install
  
  pre_build:
    commands:
      - echo Running tests...
      - npm test || echo "No tests found, continuing build"
  
  build:
    commands:
      - echo Building the application...
      - npm run build || echo "No build script found, continuing"
  
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - appspec.yml
    - index.html
    - scripts/**/*
    - public/**/*
    - dist/**/*
    - build/**/*
  discard-paths: no

cache:
  paths:
    - 'node_modules/**/*'
